name: chinaUnicom
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/chinaUnicom.js'
      - 'scripts/sfsy.js'
  schedule:   
     - cron: '56 6,16 * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Script:
    runs-on: ubuntu-latest
    env:
       PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
    steps:
      - uses: actions/checkout@main
                
      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '20'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got tough-cookie crypto-js form-data
                    
      - name: chinaUnicom
        env:
          chinaUnicomCookie: ${{secrets.CHINAUNICOMCOOKIE}}
        run: node ./scripts/chinaUnicom.js
        
      - name: sfsy
        env:
          sfsyUrl: ${{secrets.SFSYURL}}
        run: node ./scripts/sfsy.js
