name: chinaUnicom
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/chinaUnicom.js'
  schedule:   
     - cron: '12 6,12,23 * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Script:
    runs-on: ubuntu-latest
    env:
       PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '18.x'
          
      - name: Install Dependency       
        run: |
          npm install 
          npm install got tough-cookie crypto-js form-data
                    
      - name: chinaUnicom
        env:
          chinaUnicomCookie: ${{secrets.CHINAUNICOMCOOKIE}}
        run: node ./scripts/chinaUnicom.js
