name: Daily
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'daily/soocare.js'
  schedule:   
      - cron: '20 15 * * *' #北京时间23:20
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Daily:
    runs-on: ubuntu-latest
    env:
       PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '20'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got
          npm install tough-cookie
          npm install crypto-js
          
      - name: 日常
        env:
          soocareCookie: ${{secrets.SOOCARECOOKIE}}
        run: node ./daily/soocare.js
