name: 茄皇三期
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 */6 * * *'   #
 
jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
      
      - name: Display current directory
        run: |
           pwd
           ls
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: "18"
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got
          npm install tough-cookie
          npm install crypto-js
          
      - name: Run JavaScript script
        env:
          MY_SECRET: ${{ secrets.TYQHCOOKIE }}
        run: node ./scripts/tyqhV2.js  #脚本存在根目录scripts文件夹下 echo $MY_SECRET
