name: Auto-JavaScript
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
  schedule:   
    - cron: '0 */6 * * *'   #
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Auto-JS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: "18"
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got
          npm install tough-cookie
          npm install crypto-js
          
      - name: Run JavaScript script
        env:
          TYQHCOOKIE: ${{ secrets.TYQHCOOKIE }}
          chinaUnicomCookie: ${{CHINAUNICOMCOOKIE}}
        run: | #脚本存在根目录scripts文件夹下
          node ./scripts/tyqhV2.js
          node ./scripts/chinaUnicom.js
          wait
