name: Script
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/meituanV3.js'
  schedule:   
     - cron: '2 0,10,15,17,21 * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Script:
    runs-on: ubuntu-latest
    env:
       PUSH_PLUS_TOKEN: ${{secrets.PUSH_PLUS_TOKEN}}
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '20'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got
          npm install tough-cookie
          npm install crypto-js
          
      - name: 茄皇第三期
        env:
          tyqhCookie: ${{secrets.MEITUANCOOKIE}}
        run: node ./scripts/meituanV3.js
