name: qiehuang
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/run_3'
  schedule:   
     - cron: '12 */4 * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Script:
    runs-on: ubuntu-latest
    env:
       WX_PUSH_TOKEN: ${{secrets.WX_PUSH_TOKEN}}
       WX_PUSH_UIDS: ${{secrets.WX_PUSH_UIDS}}
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '20'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got tough-cookie crypto-js
        
      - name: 茄皇第三期
        env:
          tyqhCookie: ${{secrets.TYQHCOOKIE}}
        run: node ./scripts/tyqhV2.js
