name: script_once
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/run'
  schedule:   
     - cron: '02 16 * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  script_once:
    runs-on: ubuntu-latest
    env:
       WX_PUSH_TOKEN: ${{secrets.WX_PUSH_TOKEN}}
       WX_PUSH_UIDS: ${{secrets.WX_PUSH_UIDS}}
    steps:
      - uses: actions/checkout@main  #采用main分支下的
                
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '20'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install got tough-cookie crypto-js
          
      - name: 书亦烧仙草
        env:
          sysxcCookie: ${{secrets.SYSXCCOOKIE}}
        run: node ./scripts/sysxc.js
